// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview An AI agent that generates insights on student progress.
 * 
 * - generateStudentProgressInsights - A function that handles the generation of student progress insights.
 * - GenerateStudentProgressInsightsInput - The input type for the generateStudentProgressInsights function.
 * - GenerateStudentProgressInsightsOutput - The return type for the generateStudentProgressInsights function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateStudentProgressInsightsInputSchema = z.object({
  studentRecords: z.string().describe('A JSON string containing an array of student records, each including personal information, medical notes, and status.'),
});
export type GenerateStudentProgressInsightsInput = z.infer<typeof GenerateStudentProgressInsightsInputSchema>;

const GenerateStudentProgressInsightsOutputSchema = z.object({
  insights: z.string().describe('AI-generated insights on student progress, including identification of students who may need additional support or enrichment.'),
});
export type GenerateStudentProgressInsightsOutput = z.infer<typeof GenerateStudentProgressInsightsOutputSchema>;

export async function generateStudentProgressInsights(input: GenerateStudentProgressInsightsInput): Promise<GenerateStudentProgressInsightsOutput> {
  return generateStudentProgressInsightsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateStudentProgressInsightsPrompt',
  input: {schema: GenerateStudentProgressInsightsInputSchema},
  output: {schema: GenerateStudentProgressInsightsOutputSchema},
  prompt: `You are an AI assistant that analyzes student records and generates insights on their progress.

  Based on the provided student records, identify students who may need additional support or enrichment.

  Consider factors such as personal information, medical notes, and current status to provide comprehensive insights.

  Student Records: {{{studentRecords}}}
  
  Provide insights on student progress:
  `,
});

const generateStudentProgressInsightsFlow = ai.defineFlow(
  {
    name: 'generateStudentProgressInsightsFlow',
    inputSchema: GenerateStudentProgressInsightsInputSchema,
    outputSchema: GenerateStudentProgressInsightsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
