import type { Student, Staff, Donation, Event } from './types';

export const students: Student[] = [
  {
    id: 'STU001',
    name: 'Rohan Sharma',
    avatar: 'https://picsum.photos/seed/STU001/100/100',
    email: 'rohan.sharma@example.com',
    status: 'Active',
    medicalNotes: 'Mild autism spectrum disorder. Benefits from visual aids and a structured routine.',
    dateOfBirth: '2010-05-15',
  },
  {
    id: 'STU002',
    name: 'Priya Patel',
    avatar: 'https://picsum.photos/seed/STU002/100/100',
    email: 'priya.patel@example.com',
    status: 'Active',
    medicalNotes: 'Down syndrome. Requires one-on-one attention for learning new tasks. Excels in music therapy.',
    dateOfBirth: '2012-02-20',
  },
  {
    id: 'STU003',
    name: 'Amit Singh',
    avatar: 'https://picsum.photos/seed/STU003/100/100',
    email: 'amit.singh@example.com',
    status: 'On Hold',
    medicalNotes: 'Cerebral palsy. Uses a wheelchair and a communication device. Currently on medical leave.',
    dateOfBirth: '2009-11-30',
  },
  {
    id: 'STU004',
    name: 'Sneha Gupta',
    avatar: 'https://picsum.photos/seed/STU004/100/100',
    email: 'sneha.gupta@example.com',
    status: 'Inactive',
    medicalNotes: 'ADHD. Has moved to a different city and discontinued the program.',
    dateOfBirth: '2011-08-12',
  },
  {
    id: 'STU005',
    name: 'Vikram Kumar',
    avatar: 'https://picsum.photos/seed/STU005/100/100',
    email: 'vikram.kumar@example.com',
    status: 'Active',
    medicalNotes: 'Dyslexia. Shows great improvement with specialized reading software and patient guidance.',
    dateOfBirth: '2013-03-25',
  },
];

export const staff: Staff[] = [
  {
    id: 'STF001',
    name: 'Anjali Verma',
    avatar: 'https://picsum.photos/seed/STF001/100/100',
    email: 'anjali.verma@sanvedana.org',
    role: 'Special Educator',
    department: 'Academics',
  },
  {
    id: 'STF002',
    name: 'Rajesh Kumar',
    avatar: 'https://picsum.photos/seed/STF002/100/100',
    email: 'rajesh.kumar@sanvedana.org',
    role: 'Admin Manager',
    department: 'Administration',
  },
  {
    id: 'STF003',
    name: 'Dr. Meena Desai',
    avatar: 'https://picsum.photos/seed/STF003/100/100',
    email: 'meena.desai@sanvedana.org',
    role: 'Occupational Therapist',
    department: 'Therapy',
  },
  {
    id: 'STF004',
    name: 'Suresh Iyer',
    avatar: 'https://picsum.photos/seed/STF004/100/100',
    email: 'suresh.iyer@sanvedana.org',
    role: 'Volunteer Coordinator',
    department: 'Support',
  },
];

export const donations: Donation[] = [
  {
    id: 'DON001',
    donorName: 'Corporate Social Responsibility Inc.',
    amount: 75000,
    date: '2024-07-20',
    status: 'Completed',
  },
  {
    id: 'DON002',
    donorName: 'Anonymous Benefactor',
    amount: 5000,
    date: '2024-07-15',
    status: 'Completed',
  },
  {
    id: 'DON003',
    donorName: 'Mehta Family Foundation',
    amount: 25000,
    date: '2024-07-12',
    status: 'Completed',
  },
  {
    id: 'DON004',
    donorName: 'Online Fundraising Campaign',
    amount: 12000,
    date: '2024-07-10',
    status: 'Pending',
  },
  {
    id: 'DON005',
    donorName: 'Local Community Drive',
    amount: 1000,
    date: '2024-06-28',
    status: 'Failed',
  },
];

export const events: Event[] = [
  {
    id: 'EVT001',
    title: 'Annual Sports Day 2024',
    date: '2024-10-26',
    location: 'City Sports Ground',
    description: 'A day of inclusive sports and games celebrating the abilities and spirit of our wonderful students. All are welcome!',
    bannerImage: 'https://picsum.photos/seed/eventSports/1200/400',
    imageHint: 'children with disabilities sports',
    gallery: [
      { url: 'https://picsum.photos/seed/sports1/600/400', hint: 'wheelchair race' },
      { url: 'https://picsum.photos/seed/sports2/600/400', hint: 'children cheering' },
    ],
    status: 'Published',
    type: 'Upcoming',
  },
  {
    id: 'EVT002',
    title: 'World Autism Awareness Day',
    date: '2024-11-15',
    location: 'Sanvedana Center Auditorium',
    description: 'Join us for an informative session with experts and parents to foster understanding and acceptance for individuals with autism.',
    bannerImage: 'https://picsum.photos/seed/eventAutism/1200/400',
    imageHint: 'autism awareness event',
    gallery: [],
    status: 'Published',
    type: 'Upcoming',
  },
  {
    id: 'EVT003',
    title: 'ArtAbility: Student Art Exhibition',
    date: '2024-12-05',
    location: 'City Art Gallery',
    description: 'An exhibition showcasing breathtaking artwork created by our talented students. All proceeds support our art therapy program.',
    bannerImage: 'https://picsum.photos/seed/eventArt/1200/400',
    imageHint: 'childrens art exhibition',
    gallery: [],
    status: 'Draft',
    type: 'Upcoming',
  },
  {
    id: 'EVT004',
    title: 'Vocational Training Expo',
    date: '2025-01-20',
    location: 'Community Hall',
    description: 'Our older students will showcase products they have created as part of their vocational training. Come support their journey to independence.',
    bannerImage: 'https://picsum.photos/seed/eventVocational/1200/400',
    imageHint: 'vocational training fair',
    gallery: [],
    status: 'Published',
    type: 'Upcoming',
  },
  {
    id: 'EVT005',
    title: 'International Day of Persons with Disabilities',
    date: '2023-12-03',
    location: 'Sanvedana Campus',
    description: 'We celebrated the day with special performances by our students, guest speakers, and an inclusive carnival for all.',
    bannerImage: 'https://picsum.photos/seed/eventDisabilityDay/1200/400',
    imageHint: 'disability day celebration',
    gallery: [
       { url: 'https://picsum.photos/seed/disability1/600/400', hint: 'children performing music' },
       { url: 'https://picsum.photos/seed/disability2/600/400', hint: 'motivational speaker' },
    ],
    status: 'Published',
    type: 'Past',
  },
  {
    id: 'EVT006',
    title: 'Sensory-Friendly Diwali Celebration 2023',
    date: '2023-10-28',
    location: 'Sanvedana Campus Grounds',
    description: 'A special Diwali mela with reduced noise and lights, featuring stalls with handmade crafts by our students.',
    bannerImage: 'https://picsum.photos/seed/eventDiwali/1200/400',
    imageHint: 'Diwali celebration disabled children',
    gallery: [],
    status: 'Published',
    type: 'Past',
  },
];


export const dashboardMetrics = {
  totalStudents: 78,
  activeStudents: 65,
  totalStaff: 25,
  donationsThisMonth: 150000,
  socialMediaFollowers: {
    facebook: 12045,
    instagram: 8032,
    twitter: 4500,
  },
  donationHistory: [
    { month: 'Jan', total: 82000 },
    { month: 'Feb', total: 95000 },
    { month: 'Mar', total: 78000 },
    { month: 'Apr', total: 110000 },
    { month: 'May', total: 98000 },
    { month: 'Jun', total: 125000 },
    { month: 'Jul', total: 150000 },
  ],
};

export const recentStudents = students.slice(0, 3);
export const recentDonations = donations.slice(0, 3);
